---
title: "Beating Keightley"
output: html_notebook
---

This NoteBook is to look at beating our current rental situation

# Libraries
```{r}

library(ggplot2)
library(scales)
library(tidyr)
library(purrr)
library(dplyr)
```
# Functions
```{r}
Transaction_Cost <- function(price) {
  MortgageRegistration <- 178.20
  LandTransferFee <- 178.20
  
  if (price > 85000 & price < 120000){
    LandTransferFee <- 188.2
  }else{
    LandTransferFee <- 188.2 + floor(price / 100000)*20
  }
  
  StampDuty <- 0
  
  if (price > 430000 & price < 530000) {
    StampDuty = 19.19 * (price-430000)/100
  } else if (price >= 530000 & price < 750000) {
    StampDuty = 11115 + 4.75*(price-360000)/100 
  } else if (price >= 750000) {
    StampDuty = 28453 + 5.15*(price-725000)/100
  }
  
  tax = MortgageRegistration + LandTransferFee + StampDuty
  
  return(tax)
}

TrueDeposit <- function(price,deposit){
  return (deposit - Transaction_Cost(price))
}

LoanValueRatio <- function(price,deposit){
  return((price-TrueDeposit(price,deposit))/price)
}

LenderMortgageInsurance <- function(price,deposit){
  lvr <- round(LoanValueRatio(price,deposit),digits = 2)
  LMI_rate <- 0
  rates <- read.csv('LMI_RATES.csv')
  wa_stamp_duty <- 0.1
  GST <- 0.1
  
  if(lvr > 0.8) {
    LMI_rate <- case_when(
      price <= 300000 ~ rates %>% filter(LVR == lvr) %>% select(X0) %>% pull(),
      price > 300000 & price <= 500000 ~ rates %>% filter(LVR == lvr) %>% select(X300000) %>% pull(),
      price > 500000 & price <= 600000 ~ rates %>% filter(LVR == lvr) %>% select(X500000) %>% pull(),
      price > 600000 & price <= 750000 ~ rates %>% filter(LVR == lvr) %>% select(X600000) %>% pull(),
      TRUE ~ rates %>% filter(LVR == lvr) %>% select(X750000) %>% pull()
    )
  }
  LMI <- price*LMI_rate
  LMI_Net <- LMI + LMI*wa_stamp_duty
  LMI_FINAL <- LMI_Net + LMI_Net*GST
  return(LMI_FINAL)
}

TrueMortgageValue <- function(price,deposit){
  return(price - TrueDeposit(price,deposit) + LenderMortgageInsurance(price,deposit))
}

TotalInterests <- function(value,rate,term){
  return(value*rate*(term/12))
}

MinMonthlyRepayment <- function(value,rate,term){
  return((value + TotalInterests(value,rate,term))/term)
}

PrincipalMonthlyRepayment <-  function(value,term){
  return(value/term)
}

InterestMonthlyRepayment <- function(value,rate,term){
  return(MinMonthlyRepayment(value,rate,term)-PrincipalMonthlyRepayment(value,term))
}

MortgageCost <- function(value,rate,Max_Monthly_Repayment,term){
  Costs <- data.frame(0,0,value)
  names(Costs)<-c("Date","Cost","Principal")
  mortgage <- value
  timeleft <- term*12
  time <- 0
  cost <- 0
  while (mortgage > 0){
    if(Max_Monthly_Repayment < MinMonthlyRepayment(mortgage,rate,timeleft)) stop('Monthly Repayments do not meet minimum requierements')
    mortgage <- mortgage - (Max_Monthly_Repayment - InterestMonthlyRepayment(mortgage,rate,timeleft))
    cost <- InterestMonthlyRepayment(mortgage,rate,timeleft)
    timeleft <-  timeleft - 1
    time <- time +1
    monthly_cost <- data.frame(time,cost,mortgage)
    names(monthly_cost)<-c("Date","Cost","Principal")
    Costs <- rbind(Costs,monthly_cost)
  }
  return(Costs)
}

Depreciation <- function(value,rate){
  return(value*rate)
}

Maintenance <- function(value,rate,time){
  return(value*rate*time)
}

SalesAgentCost <- function(value){
  return(value * 0.03)
}

MaximumHousePrice <- function(Deposit,Rate,Max_Monthly_Repayment,Term){
  housePrice <- 0
  while (Max_Monthly_Repayment > MinMonthlyRepayment(TrueMortgageValue(housePrice,Deposit),Rate,Term*12)){housePrice <- housePrice + 1000}
  return(housePrice - 1000)
 }

MinYearsOfOwnership <- function(House_Price,Deposit,Rate,Max_Monthly_Repayment,Term,HousePriceVariation,MaintenanceRate,Fixed_Yearly_Rates){
  myMortgage <- MortgageCost(TrueMortgageValue(House_Price,Deposit),Rate,Max_Monthly_Repayment,Term)
  MaxOwnershipTime <- max(myMortgage$Date)/12
  OwnershipTime <- 1
  WeeklyCost <- data.frame(NA,NA,NA)
  names(WeeklyCost)<-c("Year","CostsAsWeeklyRent","MoreExpensiveThenCurrentRent")
  
  while (OwnershipTime <= MaxOwnershipTime){
    myMortgage_short <- myMortgage %>% filter(Date < OwnershipTime*12)
    Total_Cost <- sum(myMortgage_short$Cost) +
                  Transaction_Cost(House_Price) +
                  Depreciation(House_Price,HousePriceVariation) + 
                  Maintenance(House_Price,MaintenanceRate,OwnershipTime) +
                  SalesAgentCost(House_Price - Depreciation(House_Price,HousePriceVariation)) +
                  Fixed_Yearly_Rates*OwnershipTime
                  
    CostsAsWeeklyRent <-  Total_Cost/(OwnershipTime*12*4)
    
    MoreExpensive <- if(CostsAsWeeklyRent<Current_Rent) 'No' else 'Yes' 
    
    weekly_cost <- data.frame(OwnershipTime,CostsAsWeeklyRent,MoreExpensive)
    names(weekly_cost)<-c("Year","CostsAsWeeklyRent","MoreExpensiveThenCurrentRent")
    
    WeeklyCost <- rbind(WeeklyCost,weekly_cost)
    
    OwnershipTime = OwnershipTime + 1
    
  }
  
  WeeklyCost <- WeeklyCost %>% drop_na()
  
  if(nrow(WeeklyCost %>% filter(MoreExpensiveThenCurrentRent == 'No')) >=1) {
    MinOwnership <- WeeklyCost %>% filter(MoreExpensiveThenCurrentRent == 'No') %>% select(Year) %>% min()
  }  else if (nrow(WeeklyCost) > 1) {
    MinOwnership <- WeeklyCost %>% select(Year) %>% max()
  } else {MinOwnership <-  0}
  
  return(MinOwnership)
}

MinYearsOfOwnership_data <- function(House_Price,Deposit,Rate,Max_Monthly_Repayment,Term,HousePriceVariation,MaintenanceRate,Fixed_Yearly_Rates){
  myMortgage <- MortgageCost(TrueMortgageValue(House_Price,Deposit),Rate,Max_Monthly_Repayment,Term)
  MaxOwnershipTime <- max(myMortgage$Date)/12
  OwnershipTime <- 1
  WeeklyCost <- data.frame(NA,NA,NA)
  names(WeeklyCost)<-c("Year","CostsAsWeeklyRent","MoreExpensiveThenCurrentRent")
  
  while (OwnershipTime <= MaxOwnershipTime){
    myMortgage_short <- myMortgage %>% filter(Date < OwnershipTime*12)
    Total_Cost <- sum(myMortgage_short$Cost) +
                  Transaction_Cost(House_Price) +
                  Depreciation(House_Price,HousePriceVariation) + 
                  Maintenance(House_Price,MaintenanceRate,OwnershipTime) +
                  SalesAgentCost(House_Price - Depreciation(House_Price,HousePriceVariation)) +
                  Fixed_Yearly_Rates*OwnershipTime
                  
    CostsAsWeeklyRent <-  Total_Cost/(OwnershipTime*12*4)
    
    MoreExpensive <- if(CostsAsWeeklyRent<Current_Rent) 'No' else 'Yes' 
    
    weekly_cost <- data.frame(OwnershipTime,CostsAsWeeklyRent,MoreExpensive)
    names(weekly_cost)<-c("Year","CostsAsWeeklyRent","MoreExpensiveThenCurrentRent")
    
    WeeklyCost <- rbind(WeeklyCost,weekly_cost)
    
    OwnershipTime = OwnershipTime + 1
    
  }
  
  WeeklyCost <- WeeklyCost %>% drop_na()
  
  if(nrow(WeeklyCost %>% filter(MoreExpensiveThenCurrentRent == 'No')) >= 1) {
    MinOwnership <- WeeklyCost %>% filter(MoreExpensiveThenCurrentRent == 'No') %>% select(Year) %>% min()
  }  else if (nrow(WeeklyCost) >1) {
    MinOwnership <- WeeklyCost %>% select(Year) %>% max()
  } else {MinOwnership <-  0}
  
  return(WeeklyCost)
}

MinYearsOfOwnerships <- function(Deposit,Rate,Max_Monthly_Repayment,Term,HousePriceVariation,MaintenanceRate,Fixed_Yearly_Rates){
  OwnershipCutOffs <- data.frame(0,0)
  names(OwnershipCutOffs)<-c("HousePrice","MinimumYearsOfOwnership")
  House_Price_Max <- MaximumHousePrice(Deposit,Rate,Max_Monthly_Repayment,Term)
    
  for (House_Price in seq(0,House_Price_Max,10000)) {
    MinOwnership <- MinYearsOfOwnership(House_Price,Deposit,Rate,Max_Monthly_Repayment,Term,HousePriceVariation,MaintenanceRate,Fixed_Yearly_Rates)
    ownershipcutoff <- data.frame(House_Price,MinOwnership)
    names(ownershipcutoff)<-c("HousePrice","MinimumYearsOfOwnership")
    OwnershipCutOffs <- rbind(OwnershipCutOffs,ownershipcutoff)
  }
  return (OwnershipCutOffs)
}

```

# Fixed Parameters

```{r}
Current_Rent <- 680

Deposit <- 135000

Max_Monthly_Repayment <- 4000

Rate <- 0.04

Term <- 30

Council_Rate <- 2000

Water_Rate <- 2000

Strata <- 2000

HousePriceVariation <- 0.1

MaintenanceRate <- 0.01

Fixed_Yearly_Rates <- Council_Rate + Water_Rate + Strata

```

# Single Case

```{r}
PropertyPrice <- 450000

WeeklyCost <- MinYearsOfOwnership_data(PropertyPrice,Deposit,0.03,5000,Term,HousePriceVariation,MaintenanceRate,Fixed_Yearly_Rates)

ggplot(WeeklyCost %>% filter(Year > 0),aes(Year,CostsAsWeeklyRent,fill = MoreExpensiveThenCurrentRent)) + geom_col()
```
# The Nolan Scenario
```{r}
House_Price = 450000

Nolan <- data.frame(NA,NA,NA)
names(Nolan)<-c("MonthlyRepayments","MortGageRates","MinOwnerShip_Years")

for (monthly_repayment in seq(3000,7000,250)){
  nolan <- as.data.frame(list("MortGageRates" = seq(0.02,0.05,0.005)))
  nolan$MonthlyRepayments <- monthly_repayment
  nolan <- nolan %>% mutate(
    MinOwnerShip_Years =  pmap(., function(MonthlyRepayments,MortGageRates) MinYearsOfOwnership(
      House_Price,
      Deposit,
      Rate = MortGageRates,
      Max_Monthly_Repayment = MonthlyRepayments,
      Term,
      HousePriceVariation,
      MaintenanceRate,
      Fixed_Yearly_Rates
      )
    )
  )
  Nolan <- rbind(Nolan,nolan)
  Nolan <- Nolan %>% drop_na()
}

Nolan$MortGageRates <- as.factor(Nolan$MortGageRates)
Nolan$MonthlyRepayments <- as.factor(Nolan$MonthlyRepayments)
Nolan$MinOwnerShip_Years <- as.numeric(Nolan$MinOwnerShip_Years)

ggplot(Nolan,aes(MonthlyRepayments,MinOwnerShip_Years, color = MortGageRates)) +
    geom_point() +
    scale_color_viridis_d() +
    theme_minimal() 
```

# Repayment Sensibility
```{r}
OwnershipCutOffs <- data.frame(NA,NA,NA)
names(OwnershipCutOffs)<-c("HousePrice","MinimumYearsOfOwnership","MonthlyRepayment")

for (monthly_repayment in seq(3000,7000,250)){
  ownershipcutoffs <- MinYearsOfOwnerships(Deposit,Rate,monthly_repayment,Term,HousePriceVariation,MaintenanceRate,Fixed_Yearly_Rates)
  ownershipcutoffs$MonthlyRepayment <- monthly_repayment
  OwnershipCutOffs <- rbind(OwnershipCutOffs,ownershipcutoffs)
  OwnershipCutOffs <- OwnershipCutOffs %>% drop_na()
}

OwnershipCutOffs$MonthlyRepayment <- as.factor(OwnershipCutOffs$MonthlyRepayment)

ggplot(OwnershipCutOffs,aes(HousePrice,MinimumYearsOfOwnership, color = MonthlyRepayment)) +
    geom_line() +
    scale_color_viridis_d() +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    ggtitle('Minimum years of property ownership to beat current rental costs') +
    xlab('House Price') +
    ylab('Years') +
    scale_x_continuous(breaks = breaks_width(50000),labels=label_comma())+
    scale_y_continuous(breaks = breaks_width(1))
```
# Rate Sensibility
```{r}
OwnershipCutOffs <- data.frame(NA,NA,NA)
names(OwnershipCutOffs)<-c("HousePrice","MinimumYearsOfOwnership","Rate")

for (rate in seq(0.02,0.04,0.002)){
  ownershipcutoffs <- MinYearsOfOwnerships(Deposit,rate,Max_Monthly_Repayment,Term,HousePriceVariation,MaintenanceRate,Fixed_Yearly_Rates)
  ownershipcutoffs$Rate <- rate
  OwnershipCutOffs <- rbind(OwnershipCutOffs,ownershipcutoffs)
  OwnershipCutOffs <- OwnershipCutOffs %>% drop_na()
}

OwnershipCutOffs$Rate <- as.factor(OwnershipCutOffs$Rate)

ggplot(OwnershipCutOffs,aes(HousePrice,MinimumYearsOfOwnership, color = Rate)) +
    geom_line() +
    scale_color_viridis_d() +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    ggtitle('Minimum years of property ownership to beat current rental costs') +
    xlab('House Price') +
    ylab('Years') +
    scale_x_continuous(breaks = breaks_width(50000),labels=label_comma())+
    scale_y_continuous(breaks = breaks_width(1))
```